name: Deploy Website to S3

on:
  push:
    branches:
      - main # Change to 'master' if your branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'voting-system-vote'
          AWS_ACCESS_KEY_ID: ${{ VOTING_SYSTEM_ACCESS_KEY }} # This name must match GitHub!
          AWS_SECRET_ACCESS_KEY: ${{ VOTING_SYSTEM_SECRET_ACCESS_KEY }} # This name must match GitHub!
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: './'